module.exports = [
  {
    locn_id: 1,
    area_id: 4973,
    area_name: "Engine Assembly",
    fic_id: 6,
    fic_name: "Engine Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "ENG_PAQM_Loss",
    db_prod_plan: "ENG_PAQM_Loss",
    db_prod_actual: "ENG_PAQM_Loss",
    table_andon_loss: "LBL_PAQM_Loss_Table",
    table_prod_plan: "Planned Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  // Column Name in these tables are not proper
  {
    locn_id: 1,
    area_id: 8349,
    area_name: "FA Assy Line-1 and Line-2",
    fic_id: 133,
    fic_name: "Axle Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_user: process.env.NODE_MSSQLDB_178020_USER_LATEST,
    db_pass: process.env.NODE_MSSQLDB_178020_PASSWORD_LATEST,
    db_andon_loss: "",
    db_prod_plan: "FRONT_AXLE_ANDON_L2",
    db_prod_actual: "FRONT_AXLE_ANDON_L2",
    table_andon_loss: "",
    table_prod_plan: "JOB_COUNT",
    table_prod_actual: "JOB_COUNT",
    col_prod_plan_shift: "CONVERT(VARCHAR,SHIFT)",
    col_prod_plan_target: "TARGET",
    col_prod_plan_date: "CONVERT(VARCHAR,DATE)",
    col_prod_plan_datedot: true,
    col_prod_actual_shift: "CONVERT(VARCHAR,SHIFT)",
    col_prod_actual_value: "PRODUCTION",
    col_prod_actual_date: "CONVERT(VARCHAR,DATE)",
    col_prod_actual_datedot: true,
  },
  // Column Name in these tables are not proper
  /* {
    locn_id: 1,
    area_id: 8296,
    area_name: "RA Line-1,Line-2",
    fic_id: 133,
    fic_name: "Axle Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_user: process.env.NODE_MSSQLDB_178020_USER_LATEST,
    db_pass: process.env.NODE_MSSQLDB_178020_PASSWORD_LATEST,
    db_andon_loss: "REAR_AXLE_ANDON_L1",
    db_prod_plan: "REAR_AXLE_ANDON_L1",
    db_prod_actual: "REAR_AXLE_ANDON_L1",
    table_andon_loss: "DATA",
    table_prod_plan: "L1_JOB_COUNT",
    table_prod_actual: "L1_JOB_COUNT",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
   }, */
  {
    locn_id: 1,
    area_id: 11814,
    area_name: "Frame - Assembly Line 1",
    fic_id: 2,
    fic_name: "Frame Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "Andon_FL1",
    db_prod_plan: "Andon_FL1",
    db_prod_actual: "Andon_FL1",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "Actual_production",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Prod_Cnt",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 11815,
    area_name: "Frame - Assembly Line 2",
    fic_id: 2,
    fic_name: "Frame Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "Andon_FL2",
    db_prod_plan: "Andon_FL2",
    db_prod_actual: "Andon_FL2",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "Actual_production",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Prod_Cnt",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 807,
    area_name: "Frame Assembly Line 3 (within Prima Factory)",
    fic_id: 2,
    fic_name: "Frame Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "Andon_FL3",
    db_prod_plan: "Andon_FL2",
    db_prod_actual: "Andon_FL2",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "Actual_production",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Prod_Cnt",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 39,
    area_name: "PTCED LINE",
    fic_id: 2,
    fic_name: "Frame Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "PTCED_Andon2.0",
    db_prod_plan: "PTCED_Andon2.0",
    db_prod_actual: "PTCED_Andon2.0",
    table_andon_loss: "",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 4538,
    area_name: "HCFL Trim Line",
    fic_id: 99,
    fic_name: "Trim Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "CFL_PAQM_Loss",
    db_prod_plan: "CFL_PAQM_Loss",
    db_prod_actual: "CFL_PAQM_Loss",
    table_andon_loss: "LBL_PAQM_Loss_Table",
    table_prod_plan: "Planned Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 8152,
    area_name: "HPML Line",
    fic_id: 4,
    fic_name: "Foundry Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "HPML_ANDON",
    db_prod_plan: "HPML_ANDON",
    db_prod_actual: "HPML_ANDON",
    table_andon_loss: "hpml_Andon",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 10080,
    area_name: "Line -1  Assembly",
    fic_id: 1,
    fic_name: "Vehicle Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "AndonL1",
    db_prod_plan: "Vehicle_Production",
    db_prod_actual: "Vehicle_Production",
    table_andon_loss: "Stn_Loss_L1",
    table_prod_plan: "Planned_Production_L1",
    table_prod_actual: "Dropping_Production_L1",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Actual_Dropping",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 10086,
    area_name: "Line- 2  Assembly",
    fic_id: 1,
    fic_name: "Vehicle Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "AndonL2",
    db_prod_plan: "Vehicle_Production",
    db_prod_actual: "Vehicle_Production",
    table_andon_loss: "Stn_Loss_L2",
    table_prod_plan: "Planned_Production_L2",
    table_prod_actual: "Dropping_Production_L2",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Actual_Dropping",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 10091,
    area_name: "Line-3 Assembly",
    fic_id: 1,
    fic_name: "Vehicle Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "AndonL3",
    db_prod_plan: "Vehicle_Production",
    db_prod_actual: "Vehicle_Production",
    table_andon_loss: "Stn_loss_L3",
    table_prod_plan: "Planned_Production_L3",
    table_prod_actual: "Dropping_Production_L3",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Actual_Dropping",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 4524,
    area_name: "LP Trim Line",
    fic_id: 99,
    fic_name: "Trim Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "LP_Andon2.0",
    db_prod_plan: "LP_Andon2.0",
    db_prod_actual: "LP_Andon2.0",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  // Column Name in these tables are not proper
  {
    locn_id: 1,
    area_id: 8381,
    area_name: "Main Assembly Line 2",
    fic_id: 120,
    fic_name: "Transmission FIC",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "",
    db_prod_plan: "TRANSMISSION_ANDON_L2",
    db_prod_actual: "TRANSMISSION_ANDON_L2",
    table_andon_loss: "",
    table_prod_plan: "L2_JOB_COUNT",
    table_prod_actual: "L2_JOB_COUNT",
    col_prod_plan_shift: "CONVERT(VARCHAR,SHIFT)",
    col_prod_plan_target: "TARGET",
    col_prod_plan_date: "CONVERT(VARCHAR,DATE)",
    col_prod_plan_datedot: true,
    col_prod_actual_shift: "CONVERT(VARCHAR,SHIFT)",
    col_prod_actual_value: "PRODUCTION",
    col_prod_actual_date: "CONVERT(VARCHAR,DATE)",
    col_prod_actual_datedot: true,
  },
  {
    locn_id: 1,
    area_id: 12086,
    area_name: "New Trim Line",
    fic_id: 99,
    fic_name: "Trim Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "New_Trim_Andon",
    db_prod_plan: "New_Trim_Andon",
    db_prod_actual: "New_Trim_Andon",
    table_andon_loss: "Trim_Andon",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 4542,
    area_name: "Prima Trim Line",
    fic_id: 99,
    fic_name: "Trim Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "PTL_Andon2.0",
    db_prod_plan: "PTL_Andon2.0",
    db_prod_actual: "PTL_Andon2.0",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "Actual_production",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "Prod_Cnt",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
  {
    locn_id: 1,
    area_id: 4539,
    area_name: "SFC / Tilt Cab Trim Line",
    fic_id: 99,
    fic_name: "Trim Factory",
    api_url: process.env.NODE_ANDON_API_URL_JSR,
    db_andon_loss: "SFC_Tilt_Andon2.0",
    db_prod_plan: "SFC_Tilt_Andon2.0",
    db_prod_actual: "SFC_Tilt_Andon2.0",
    table_andon_loss: "Stn_loss",
    table_prod_plan: "Planned_Production",
    table_prod_actual: "HourlyProduction",
    col_prod_plan_shift: "Shift_no",
    col_prod_plan_target: "Planned_Production",
    col_prod_plan_date: "CAST(Date_id as Date)",
    col_prod_plan_datedot: false,
    col_prod_actual_shift: "Shift_no",
    col_prod_actual_value: "H_Production",
    col_prod_actual_date: "CAST(Date_id as Date)",
    col_prod_actual_datedot: false,
  },
];
